stages:
- name: compile
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: |-
        ls -lah
        git status

        touch asri
        echo "ini dari script yang pertama" >> asri
        echo "hai asri" > ./deployment.yml
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        ls -lah
        echo "------ cat asri file"
        cat ./asri
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
