stages:
- name: compile
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: |-
        ls -lah
        git status
        git fetch --all --tags --prune
        git checkout tags/stable -b master
        touch asri
        echo "ini dari script yang pertama" >> asri
        docker ps
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        ls -lah
        echo "------ cat asri file"
        cat ./asri
timeout: 60
