stages:
- name: compile
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: |-
        ls -lah
        git status

        touch asri
        echo "ini dari script yang pertama" >> asri
        echo "deployment sebelum di edit"

        echo "hai asri" > ./deployment.yaml
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        ls -lah
        echo "------ cat asri file"
        cat ./asri
  - publishImageConfig:
      dockerfilePath: ./deployment/Dockerfile
      buildContext: .
      tag: asridjufri/ut-demo:stable
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment/deployment.yaml
timeout: 60
