stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: asridjufri/ut-demo:stable
      pushRemote: true
      registry: index.docker.io
    when:
      branch:
        include:
        - master
      event:
        include:
        - tag
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - tag
timeout: 60
