stages:
- name: compile
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: git status
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: asridjufri/ut-demo:stable
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch: {}
      event: {}
timeout: 60
