apiVersion: apps/v1
kind: Deployment
metadata:
  name: ut-deployment
  labels:
    app: ut

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ut-deployment
  template:
    metadata:
      name: my-ut
      labels:
        app: ut-deployment
    spec:
      containers:
        - name: container-ut-demo
          image: asridjufri/ut-demo
          ports:
            - containerPort: 9000
